database/seeders/DatabaseSeeder.php
Ultimo commit donde agregamos usuarios reales.
=> Se agrega seeder DatabaseSeeder con los usuarios admin y asesor

database/migrations/2022_05_15_201514_create_dato2s_table.php
Se agrega campo longtext al campo dirección física en lugar del campo dirección.
=> Se corrije tipo de campo longtext

database/migrations/2022_05_15_201514_create_dato2s_table.php
Se agrega un cambio al campo direccion correspondecia como longtext.
=> Se agrega cambio al campo direccion correspondencia como longtext

database/seeders/DatabaseSeeder.php, public/js/app.js, resources/js/Components/TablaCustomer.vue, resources/js/Components/TablaDato1.vue, resources/js/Components/TablaDato2.vue, resources/js/Components/TablaDato3.vue, resources/js/Components/TablaDato4.vue, resources/js/Components/TablaDato5.vue, resources/js/Components/TablaDato6.vue, resources/js/Components/TablaDato7.vue, resources/js/Components/TablaDato8.vue, resources/js/Components/TablaDato9.vue, resources/js/Components/TablaTelefono.vue
Corrijo correo rol admin, agrego nombre de cada tabla en sus vistas como tabla.
=> Corrijo Admin y agrego nombre de cada tabla en vista como tabla

app/Http/Controllers/BusquedaMultipleController.php, public/js/app.js, resources/js/Layouts/AppLayout.vue, resources/js/Pages/BusquedaMultiple/BusquedaMultiple.vue, routes/web.php
Se agrega Módulo Búsqueda Múltiple en el Controller y y en las Vistas
=> Se agreaga Módulo BusquedaMultiple

app/Http/Controllers/BusquedaMultipleController.php, app/Http/Controllers/SecurityController.php, app/Models/User.php, config/jetstream.php, public/js/app.js, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Auth/Register.vue, resources/js/Pages/BusquedaMultiple/BusquedaMultiple.vue, resources/js/Pages/Security/Create.vue, resources/js/Pages/Security/Edit.vue, resources/js/Pages/Security/Index.vue, resources/js/Pages/Security/Users.vue, routes/web.php
creación de Modulo Scurity Usuarios
=> creación de Modulo Scurity Usuarios

app/Http/Controllers/SecurityController.php, public/css/app.css, public/js/app.js, resources/css/buttons.css, resources/js/Jetstream/Welcome.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Security/Create.vue, resources/js/Pages/Security/Edit.vue, resources/js/Pages/Security/Index.vue, resources/js/Pages/Security/Users.vue, routes/web.php
Se agrega botones al modulo dashboard welcome y se actualiza modulo usuarios
=> Se realizan correcciones y se actualiza modulos usuarios y dashboard

app/Http/Controllers/BusquedaCamposController.php, public/css/app.css, public/js/app.js, resources/js/Components/TablaCustomer.vue, resources/js/Components/TablaDato1.vue, resources/js/Components/TablaDato2.vue, resources/js/Components/TablaDato3.vue, resources/js/Components/TablaDato4.vue, resources/js/Components/TablaDato5.vue, resources/js/Components/TablaDato6.vue, resources/js/Components/TablaDato7.vue, resources/js/Components/TablaDato8.vue, resources/js/Components/TablaDato9.vue, resources/js/Components/TablaTelefono.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/BusquedaCampos/BusquedaCampos.vue, routes/web.php
Se implementa el módulo búsqueda múltiple con pestaña en layout y con tildes en el texto.
=> Se agrega tildes en módulo búsqueda

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/BusquedaCamposController.php, app/Http/Controllers/BusquedaMultipleController.php, app/Http/Controllers/CustomerController.php, app/Http/Controllers/Dato1Controller.php, app/Http/Controllers/Dato2Controller.php, app/Http/Controllers/Dato3Controller.php, app/Http/Controllers/Dato4Controller.php, app/Http/Controllers/Dato5Controller.php, app/Http/Controllers/Dato6Controller.php, app/Http/Controllers/Dato7Controller.php, app/Http/Controllers/Dato8Controller.php, app/Http/Controllers/Dato9Controller.php, app/Http/Controllers/SecurityController.php, app/Http/Controllers/TelefonoController.php, database/migrations/2022_07_18_230044_create_cache_table.php
Se agrega al proyecto la implementación de la cache de Laravel con database como driver de cache.
=> Implementacion de cache

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/BusquedaCamposController.php, app/Http/Controllers/BusquedaMultipleController.php, app/Http/Controllers/CustomerController.php, app/Http/Controllers/Dato1Controller.php, app/Http/Controllers/Dato2Controller.php, app/Http/Controllers/Dato3Controller.php, app/Http/Controllers/Dato4Controller.php, app/Http/Controllers/Dato5Controller.php, app/Http/Controllers/Dato6Controller.php, app/Http/Controllers/Dato7Controller.php, app/Http/Controllers/Dato8Controller.php, app/Http/Controllers/Dato9Controller.php, app/Http/Controllers/SecurityController.php, app/Http/Controllers/TelefonoController.php, database/seeders/DatabaseSeeder.php
Se corrige lapso de tiempo de cache y se agrega nuevos usuarios con rol asesor
=> Lapso de tiempo de cache y dos nuevos usuarios asesor

database/seeders/DatabaseSeeder.php
Se hablara con @esviren para aclaración de este caso de duplicidad de usuario.
=> Se quita el usuario Nubia por duplicidad

config/cache.php, public/js/app.js, resources/js/Components/TablaDato1.vue, resources/js/Components/TablaDato2.vue, resources/js/Components/TablaDato3.vue, resources/js/Components/TablaDato4.vue, resources/js/Components/TablaDato5.vue, resources/js/Components/TablaDato6.vue, resources/js/Components/TablaDato7.vue, resources/js/Components/TablaDato8.vue, resources/js/Components/TablaDato9.vue, resources/js/Components/TablaTelefono.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Dato1/Dato1.vue, resources/js/Pages/Dato2/Dato2.vue, resources/js/Pages/Dato3/Dato3.vue, resources/js/Pages/Dato4/Dato4.vue, resources/js/Pages/Dato5/Dato5.vue, resources/js/Pages/Dato6/Dato6.vue, resources/js/Pages/Dato9/Dato9.vue, resources/js/Pages/Telefono/Telefono.vue
Se realiza pull request con cambios en los nombres de las tablas.
=> Se restablece nombres de las tablas

database/seeders/DatabaseSeeder.php, public/js/app.js, resources/js/Components/TablaDato3.vue, resources/js/Components/TablaDato4.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Dato3/Dato3.vue, resources/js/Pages/Dato4/Dato4.vue
Agregar  seeder y corregir Tribunales 1 y2
=> Agregar seeder usuarios y corregir tribunales

app/Http/Controllers/Dato12Controller.php, app/Models/dato12.php, database/factories/Dato12Factory.php, database/migrations/2022_09_20_210354_create_dato12s_table.php, database/seeders/Dato12Seeder.php, public/js/app.js, resources/js/Components/TablaDato12.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Datos/Dato12.vue, routes/web.php
Creación de Modelo y Vista para Datos 12
=> Creacion de Vista datos 12

app/Http/Controllers/Dato15Controller.php, app/Models/dato15.php, database/factories/Dato15Factory.php, database/migrations/2022_09_22_190430_create_dato15s_table.php, database/seeders/Dato15Seeder.php, public/js/app.js, resources/js/Components/TablaDato15.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Datos/Dato15.vue, routes/web.php
=> Se crea el modulo dato15s -mfsc

app/Http/Controllers/Dato16Controller.php, app/Models/dato16.php, database/factories/Dato16Factory.php, database/migrations/2022_09_26_230450_create_dato16s_table.php, database/seeders/Dato16Seeder.php, public/js/app.js, resources/js/Components/TablaDato16.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Datos/Dato16.vue, routes/web.php
creation of table dato15s -mfsc and add data base
=> creation of table dato15s -mfsc

app/Http/Controllers/Dato24Controller.php, app/Models/dato24.php, database/factories/Dato24Factory.php, database/migrations/2022_09_27_215752_create_dato24s_table.php, database/seeders/Dato24Seeder.php, resources/js/Components/TablaDato24.vue, resources/js/Pages/Datos/Dato24.vue
Creation of Table Dato24 -nfsc with simple view
=> Creation of Table Dato24 -nfsc with simple view

app/Http/Controllers/Dato23Controller.php, app/Models/Dato23.php, database/factories/Dato23Factory.php, database/migrations/2022_10_03_193011_create_dato23s_table.php, database/seeders/Dato23Seeder.php, public/js/app.js, resources/js/Components/TablaDato23.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Datos/Dato23.vue, routes/web.php
Se crea vista con controlador, modelo, migracion, factory y seeders de Datos 23
=> Creacion de Datos 23 -mfsc Vista Individual

public/js/app.js, resources/js/Layouts/AppLayout.vue, routes/web.php
Se genera la vista Dato27 funcional con los controladores y el modelo.
=> Creacion de Dato27 -mfsc Vista Individual

app/Http/Controllers/Dato27Controller.php, app/Models/Dato27.php, database/factories/Dato27Factory.php, database/migrations/2022_10_10_003858_create_dato27s_table.php, database/seeders/Dato27Seeder.php, resources/js/Components/TablaDato27.vue, resources/js/Pages/Datos/Dato27.vue
Se corrige commit de Creacion Dato 27.
=> Correccion de Dato27

app/Http/Controllers/Dato31Controller.php, app/Models/Dato31.php, database/factories/Dato31Factory.php, database/migrations/2022_10_10_061351_create_dato31s_table.php, database/seeders/Dato31Seeder.php, public/js/app.js, resources/js/Components/TablaDato31.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Datos/Dato31.vue, routes/web.php
Se crea dato 31, es funcional.
=> Creacion de Dato 31 -mfsc Vista Individual

app/Http/Controllers/Dato30Controller.php, app/Models/dato30.php, database/factories/Dato30Factory.php, database/migrations/2022_10_10_170348_create_dato30s_table.php, database/seeders/Dato30Seeder.php, public/js/app.js, resources/js/Components/TablaDato30.vue, resources/js/Pages/Datos/Dato30.vue, routes/web.php
Create basic view Dato30 -mfsc
=> Create basic view Dato30 -mfsc

app/Http/Controllers/Dato35Controller.php, app/Models/Dato35.php, database/factories/Dato35Factory.php, database/migrations/2022_10_10_221119_create_dato35s_table.php, database/seeders/Dato35Seeder.php, public/js/app.js, resources/js/Components/TablaDato35.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Datos/Dato35.vue, routes/web.php
Se añade ultima tabla de datos por parte de la rama juanca
=> Creación Dato 35 -mfsc Vista Individual

app/Http/Controllers/Dato10Controller.php, public/js/app.js, resources/js/Pages/Datos/Dato36.vue, resources/js/Pages/MenuTablas.vue
=> Correcion COntroles

app/Http/Controllers/Dato14Controller.php, app/Http/Controllers/Dato16Controller.php
Corrección controladores 14-16
=> Correción controladores 14-16

app/Http/Controllers/BusquedaCamposController.php, app/Models/Dato19.php, app/Models/dato14.php, public/js/app.js, resources/js/Pages/BusquedaCampos/BusquedaCampos.vue
Se agrega al modulo busqueda por campos las tablas faltantes.
=> Se agregan a vista busqueda por campos las tablas faltantes

app/Http/Controllers/Dato12Controller.php, public/js/app.js, resources/js/Components/TablaDato11.vue, resources/js/Components/TablaDato23.vue, resources/js/Components/TablaDato24.vue, resources/js/Components/TablaDato25.vue, resources/js/Components/TablaDato26.vue, resources/js/Components/TablaDato31.vue, resources/js/Components/TablaDato33.vue, resources/js/Components/TablaDato35.vue, resources/js/Components/TablaDato36.vue, resources/js/Jetstream/Welcome.vue, resources/js/Pages/Datos/Dato26.vue
Se corrige múltiples tablas y capa de seguridad en dashboard.
=> Commit de correccion de errores

app/Http/Controllers/Dato37Controller.php, app/Http/Controllers/Dato38Controller.php, app/Models/Dato37.php, app/Models/Dato38.php, database/factories/Dato37Factory.php, database/factories/Dato38Factory.php, database/migrations/2022_10_18_170425_create_dato37s_table.php, database/migrations/2022_10_19_001502_create_dato38s_table.php, database/seeders/Dato37Seeder.php, database/seeders/Dato38Seeder.php, resources/js/Components/TablaDato37.vue, resources/js/Components/TablaDato38.vue, resources/js/Pages/Datos/Dato37.vue, resources/js/Pages/Datos/Dato38.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
Se agregan tablas dato 37 y dato 38, se agregan sus respectivas vistas.
=> Se crean tablas dato 37 y dato 38 -mfsc vista individual

app/Http/Controllers/BusquedaCamposController.php, app/Http/Controllers/Dato1Controller.php, app/Models/Dato1.php, composer.json, composer.lock, config/app.php, database/migrations/2022_05_15_201459_create_dato1s_table.php, database/seeders/DatabaseSeeder.php, package-lock.json, resources/js/Components/TablaDato1.vue, resources/js/Pages/Datos/Dato1.vue, resources/js/Pages/MenuTablas.vue, resources/js/Pages/Welcome.vue
Se realizan cambios a la tabla dato1 para subir una actualización de nuevos campos.
=> Cambios realizados a la migracion dato1s

database/migrations/2022_05_15_201459_create_dato1s_table.php
Se realizan cambios rapidos de los campos en la tabla dato1s sobre campos que tenian double y se cambian por varchar.
=> Se cambian los campos de que eran double en la migracion por texto

app/Http/Controllers/Dato39Controller.php, app/Models/Dato39.php, database/factories/Dato39Factory.php, database/migrations/2023_03_29_041329_create_dato39s_table.php, database/seeders/Dato39Seeder.php, package-lock.json, public/css/app.css, resources/js/Components/TablaDato39.vue, resources/js/Pages/Datos/Dato38.vue, resources/js/Pages/Datos/Dato39.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
Se crea la tabla datos 39 con mfsc creando la migracion apartir de la creacion del modelo y tambien se crea factory, seeder y controlador.
=> Se crean tabla dato 39 con -mfsc funcional

app/Http/Controllers/BuscarCedulaController.php, public/css/app.css, resources/js/Pages/BuscarCedula/BuscarCedula.vue
Se crea en la vista buscar cedula las tablas dato 37, dato 38 y dato 39 y se agregan sus funcionalidades en el controlador.
=> Se agregan a la vista buscarcedula las tablas dato37, dato38, dato39

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/Dato40Controller.php, app/Models/Dato40.php, database/factories/Dato40Factory.php, database/migrations/2023_04_22_161036_create_dato40s_table.php, database/seeders/Dato40Seeder.php, resources/js/Components/TablaDato40.vue, resources/js/Pages/BuscarCedula/BuscarCedula.vue, resources/js/Pages/Datos/Dato40.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
Agrego modelo dato 40 con migracion, factory, seeder y controlador.
=> Agrego modelo Dato40 con -mfsc

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/BusquedaCamposController.php, app/Http/Controllers/Dato41Controller.php, app/Models/Dato41.php, database/factories/Dato41Factory.php, database/migrations/2023_04_27_002140_create_dato41s_table.php, database/seeders/Dato41Seeder.php, resources/js/Components/TablaDato41.vue, resources/js/Pages/BuscarCedula/BuscarCedula.vue, resources/js/Pages/BusquedaCampos/BusquedaCampos.vue, resources/js/Pages/Datos/Dato41.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
=> Agrego Dato 41

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/BusquedaCamposController.php, app/Http/Controllers/Dato43Controller.php, app/Models/Dato43.php, database/factories/Dato43Factory.php, database/migrations/2023_05_11_144501_create_dato43s_table.php, database/seeders/Dato43Seeder.php, resources/js/Components/TablaDato42.vue, resources/js/Components/TablaDato43.vue, resources/js/Pages/BuscarCedula/BuscarCedula.vue, resources/js/Pages/BusquedaCampos/BusquedaCampos.vue, resources/js/Pages/Datos/Dato43.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
Agrego dato 43 con modelo, factory, seeder y controlador.
=> Agrego Dato 43 con -mfsc

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/Dato44Controller.php, app/Models/Dato44.php, database/factories/Dato44Factory.php, database/migrations/2023_05_11_144501_create_dato43s_table.php, database/migrations/2023_06_21_145908_create_dato44s_table.php, database/seeders/Dato44Seeder.php, resources/js/Components/TablaDato44.vue, resources/js/Pages/Datos/Dato44.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
Se crea la tabla dato44 con sus respectivos componentes
=> Se crea dato44s -mfsc

app/Http/Controllers/BusquedaCamposController.php, resources/js/Pages/BuscarCedula/BuscarCedula.vue, resources/js/Pages/BusquedaCampos/BusquedaCampos.vue
Agrego en vistas de las tablas la tabla dato44
=> Agrego vistas generales

app/Http/Controllers/BuscarCedulaController.php, app/Http/Controllers/BusquedaCamposController.php, app/Http/Controllers/Dato45Controller.php, app/Models/Dato45.php, database/factories/Dato45Factory.php, database/migrations/2023_06_27_002459_create_dato45s_table.php, database/seeders/Dato45Seeder.php, resources/js/Components/TablaDato45.vue, resources/js/Pages/BuscarCedula/BuscarCedula.vue, resources/js/Pages/BusquedaCampos/BusquedaCampos.vue, resources/js/Pages/Datos/Dato45.vue, resources/js/Pages/MenuTablas.vue, routes/web.php
Agrego la tabla dato45 al repo
=> Dato45s -mfsc
